import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import localFont from "next/font/local";

const mova = localFont({ src: "../fonts/mova.otf", variable: "--font-mova" });

const arenq = localFont({
  src: "../fonts/arenq.otf",
  variable: "--font-arenq",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${mova.variable} ${arenq.variable}`}>{children}</body>
    </html>
  );
}
