import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local";

import { logo } from "@/public";

const mova = localFont({ src: "../fonts/mova.otf", variable: "--font-mova" });

const arenq = localFont({
  src: "../fonts/arenq.otf",
  variable: "--font-arenq",
});

export const metadata: Metadata = {
  title: "Sean | Portfolio",
  description: "Generated by create next app",
  icons: logo.src,
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${mova.variable} ${arenq.variable}`}>{children}</body>
    </html>
  );
}
